"""empty message

Revision ID: 28fcdc23567e
Revises: 4ef753beab3b
Create Date: 2025-02-19 04:02:17.819730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28fcdc23567e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menuID', sa.Integer(), nullable=False))
        batch_op.drop_constraint('dish_menu_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu', ['menuID'], ['id'])
        batch_op.drop_column('menu_id')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurantID', sa.Integer(), nullable=False))
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               nullable=True,
                postgresql_using="created::timestamp without time zone")
        batch_op.alter_column('last_updated',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               nullable=True,
               postgresql_using="last_updated::timestamp without time zone")
        batch_op.alter_column('categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint('menu_restaurant_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurant', ['restaurantID'], ['id'])
        batch_op.drop_column('restaurant_id')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menu_restaurant_id_fkey', 'restaurant', ['restaurant_id'], ['id'])
        batch_op.alter_column('categories',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('restaurantID')

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dish_menu_id_fkey', 'menu', ['menu_id'], ['id'])
        batch_op.drop_column('menuID')

    # ### end Alembic commands ###
