"""empty message

Revision ID: 2a9188c3d8c2
Revises: ab85b555086d
Create Date: 2025-03-20 16:02:08.558932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9188c3d8c2'
down_revision = 'ab85b555086d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_news', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###
