"""empty message

Revision ID: 2b7f5a04dce2
Revises: 114879b8b880
Create Date: 2025-03-16 05:06:50.980568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7f5a04dce2'
down_revision = '114879b8b880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'])
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('subject')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
