"""empty message

Revision ID: 2dd67449fb91
Revises: e0de18d0c46e
Create Date: 2025-02-27 02:24:01.301467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd67449fb91'
down_revision = 'e0de18d0c46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_URL', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('image_URL')

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
