"""empty message

Revision ID: 635dfbfcc486
Revises: 74fd79733774
Create Date: 2025-02-23 12:16:21.810617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '635dfbfcc486'
down_revision = '74fd79733774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_URL', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_data')
        batch_op.drop_column('extension')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('image_URL')

    # ### end Alembic commands ###
