"""empty message

Revision ID: 698286963c4a
Revises: 28fcdc23567e
Create Date: 2025-02-19 22:33:56.341717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698286963c4a'
down_revision = '28fcdc23567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('categories',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('categories',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
