"""empty message

Revision ID: 74fd79733774
Revises: 8d2f8ffa4fe4
Create Date: 2025-02-22 20:31:32.575283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fd79733774'
down_revision = '8d2f8ffa4fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('extension', sa.String(length=10), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('extension')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
