"""empty message

Revision ID: 848ccc7408a5
Revises: cdbd01aec268
Create Date: 2025-03-10 14:43:11.279339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848ccc7408a5'
down_revision = 'cdbd01aec268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
