"""empty message

Revision ID: ab85b555086d
Revises: bbfc330b549f
Create Date: 2025-03-20 13:49:27.451226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab85b555086d'
down_revision = 'bbfc330b549f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_username', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_news', schema=None) as batch_op:
        batch_op.drop_column('restaurant_username')

    # ### end Alembic commands ###
