"""empty message

Revision ID: cdbd01aec268
Revises: 06bd55187440
Create Date: 2025-03-10 02:57:55.040165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbd01aec268'
down_revision = '06bd55187440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('social_networks',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=650),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('social_networks',
               existing_type=sa.String(length=650),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
